-- MySQL Script generated by MySQL Workbench
-- lun 27 nov 2017 05:25:59 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema wallethub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wallethub` ;

-- -----------------------------------------------------
-- Schema wallethub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wallethub` ;
SHOW WARNINGS;
USE `wallethub` ;

-- -----------------------------------------------------
-- Table `wallethub`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wallethub`.`logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wallethub`.`logs` (
  `date` VARCHAR(45) NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `request` VARCHAR(250) NOT NULL,
  `status` INT NOT NULL,
  `user_agent` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`date`, `ip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `wallethub`.`blocked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wallethub`.`blocked` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wallethub`.`blocked` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(15) NOT NULL,
  `comments` VARCHAR(250) NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
